# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
  buildConfiguration: 'Release'
  springPetRepository: 'spring-petclinic'
  mySqlRepository: 'mysql'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'secret'
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

resources:
  repositories:
  - repository: azure_test
    type: github
    name: jgoldsmith613/azure_test
    endpoint: jgoldsmith613
  - repository: config
    type: github
    name: jgoldsmith613/spring-petclinic-config
    endpoint: jgoldsmith613

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: Cache@2
      displayName: Cache Maven local repo
      inputs:
        key: 'maven | "$(Agent.OS)" | **/pom.xml'
        restoreKeys: |
          maven | "$(Agent.OS)"
          maven
        path: $(MAVEN_CACHE_FOLDER)

    - script: mvn install -B -e
    - task: Maven@3
      displayName: 'Build the maven artifact'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: Docker@2
      displayName: 'Build and push the image to container registry'
      inputs:
        command: buildAndPush
        buildContext: $(Build.Repository.LocalPath)
        repository: $(springPetRepository)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: 'azure-container-registry'
        tags: |
          $(tag)
    
    - publish: '$(Build.SourcesDirectory)/manifests'
      artifact: manifests

- stage: 'Deploy_Dev'
  displayName: 'Deploy to Dev'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'openshift.dev'
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: manifests
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: 'azure-container-registry'
              kubernetesServiceConnection: 'openshift-dev-1652736334320'
              namespace: 'dev'
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: 'openshift-dev-1652736334320'
              namespace: 'dev'
              manifests: |
                $(Pipeline.Workspace)/manifests/dev/cm.yaml
                $(Pipeline.Workspace)/manifests/dev/secret.yaml
                $(Pipeline.Workspace)/manifests/dev/deployment.yaml
                $(Pipeline.Workspace)/manifests/dev/service.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(ACR_RegistryName)/$(springPetRepository):$(tag)
                $(ACR_RegistryName)/$(mySqlRepository):latest

- stage: 'Deploy_Stage'
  displayName: 'Deploy to Stage'
  dependsOn: Deploy_Dev
  jobs:
  - deployment: Secret
    displayName: Create Image Pull Secret
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'openshift.stage'
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: manifests
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: 'azure-container-registry'
              kubernetesServiceConnection: 'openshift-stage-1652464815216'
              namespace: 'stage'
  - deployment: kustomize
    displayName: Update Kustomize Image
    dependsOn: Secret
    pool:
      vmImage: 'ubuntu-latest'
    container: 'quay.io/wpernath/kustomize-ubi:latest'
    environment: 'openshift.stage'
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: config
            persistCredentials: true
          - script: |
              cd envs/stage
              kustomize edit set image $(ACR_RegistryName)/$(springPetRepository)=$(ACR_RegistryName)/$(springPetRepository):$(tag)
          - publish: '$(Build.SourcesDirectory)/envs/stage'
            artifact: stage
  - deployment: update_git
    displayName: Update git stage
    dependsOn: kustomize
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'openshift.stage'
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: config
            persistCredentials: true
          - download: current
            artifact: stage
          - script: |
              git config --global user.email pipeline@demo.com & git config --global user.name "Pipeline"
            workingDirectory: $(System.DefaultWorkingDirectory)
          
          - script: |
              git checkout -b main
              cp ../stage/* envs/stage/.
              git add -A
              git commit -m "deployment $(tag)"
              git push --set-upstream origin main

